FROM python:3.11-slim

# Install required packages
RUN pip install kafka-python protobuf==4.24.4

# Copy scripts
COPY scripts/ /scripts/
COPY descriptors/ /descriptors/

# Create working directory
WORKDIR /app

CMD ["python", "/scripts/produce_messages.py"]